[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
test = "test"
script = "script"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@chainlink/=node_modules/@chainlink/",
]

[profile.ci]
fuzz.runs = 1000
invariant.runs = 100

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

[doc]
out = "docs"
include = ["contracts"]

